name: di_art
description: Proper DI for Flutter
version: 0.0.1
#author:
#homepage:

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.5
  logart: ^0.0.2
